services:
  sillytavern:
    image: ghcr.io/sillytavern/sillytavern:latest
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: ${CPUS}
          memory: ${MEMORY_LIMIT}
    environment:
      - NODE_ENV=production
      - FORCE_COLOR=1
      - SILLYTAVERN_LISTEN=true
      - SILLYTAVERN_HEARTBEATINTERVAL=${SILLYTAVERN_HEARTBEAT_INTERVAL}
      - SILLYTAVERN_WHITELISTMODE=${SILLYTAVERN_WHITELIST_MODE}
      - SILLYTAVERN_BASICAUTHMODE=${SILLYTAVERN_BASICAUTH_MODE}
      - SILLYTAVERN_BASICAUTHUSER_USERNAME=${SILLYTAVERN_BASICAUTH_USER}
      - SILLYTAVERN_BASICAUTHUSER_PASSWORD=${SILLYTAVERN_BASICAUTH_PASSWORD}
      - SILLYTAVERN_ENABLEUSERACCOUNTS=${SILLYTAVERN_ENABLE_USER_ACCOUNTS}
    ports:
      - ${HOST_IP}:${SILLYTAVERN_WEB_PORT}:8000
    volumes:
      - ${APP_PATH}/config:/home/node/app/config
      - ${APP_PATH}/data:/home/node/app/data
      - ${APP_PATH}/plugins:/home/node/app/plugins
      - ${APP_PATH}/extensions:/home/node/app/public/scripts/extensions/third-party
    healthcheck:
      test: ["CMD", "node", "src/healthcheck.js"]
      interval: 30s
      timeout: 10s
      start_period: 20s
      retries: 3
    labels:
      createdBy: "bt_apps"
    networks:
      - baota_net

networks:
  baota_net:
    external: true
